version: '3.8'  
services:
  app:
    build: 
      context: .
      target: production
    image: todo-app:production
    volumes:
      - .:/app
    ports:
      - "3010:3000"
    env_file:
      - .env
    depends_on:
      - db
  db: 
    image: postgres:15
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - URL=$DATABASE_URL
      - POSTGRES_DB=$PROD_DATABASE
    
volumes:
  pg-dev-data:
