name: Web Application CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Navigate to repository directory
        run: cd todo-web-app

      - name: Install dependencies
        run: npm install

      - name: Run linting and code formatting
        run: npm run lint

      - name: Build the application
        run: npm run build

      - name: Run automated tests
        run: npm test

      - name: Deploy to production
        if: success()
        run: |
          # Add deployment script/command here
          echo "Deployment to production environment successful"

      - name: Notify on failure
        if: failure()
        run: |
          # Add error reporting and notification logic here
          echo "Pipeline failed! Please check the logs for details."
